### ISSUE TITLE
Upgrade to support Laravel 9

### ISSUE THREAD

**Issue by DmitrySidorenkoShim** [bringyourownideas/laravel-sitemap#9]
Hello,

do you have plans to upgrade the package 
for supporting Laravel 9?

It would be awesome if so.
Because I have to upgrade one project to latest Laravel version
but can't do this because of "bringyourownideas/laravel-sitemap"

Thank you in advance

**Comment by spekulatius** [comment]
Hey @DmitrySidorenkoShim,

yeah, Laravel 9 is on the plan. I've just got a lot of things on at the moment. Do you think you wanna start a branch and give it a try/make a start?

Cheers,
Peter

**Comment by DmitrySidorenkoShim** [comment]
hey,

I quickly tried with changes
but you have `"vdb/php-spider"` package required
in your composer.json
it requires `"symfony/finder": "^3.0.0||^4.0.0||^5.0.0"`

and in Laravel 9 it is already `"symfony/finder": "^6.0"`

do you have ideas?
should I also try to write an issue in this package's repo?

this is only one problem we need to solve for composer.json

Dimon

UPD.
created the [issue](https://github.com/mvdbos/php-spider/issues/82)

**Comment by spekulatius** [comment]
Hey @DmitrySidorenkoShim 

yeah, we need to get the updates in line first. Then we can check proper if everything works. Let's see what Matthijs says.

Cheers,
Peter

**Comment by DmitrySidorenkoShim** [comment]
hey @spekulatius,

no one from `"vdb/php-spider"` package responded so far
and last activity for this package was more than a year ago 
I think it is not supported any more...

if we can't find another solution we can fork this package and upgrade it
but it would be not the best solution


I will check forks,
this package has 239 of them 
maybe one of them is already updated


upd.
created [pull request](https://github.com/mvdbos/php-spider/pull/83)

one quick question
what is your workflow?
should I also create a fork for changes to your package?

upd2.
I started with your package
and looks like it support only `"vdb/php-spider": "^v0.5.2"`
but they have latest version `0.6.2` right now
[the difference ](https://github.com/mvdbos/php-spider/compare/v0.5.2...v0.6.2)

can you, please check and update your package?
because you know it better and know how it should works

first thing I found:
they moved StatsHandler class from `/src` to `/example` folder
and it is not available any more for using


upd3.
ok, ok, I have made changes
and no errors right now
here is the output:

> php artisan sitemap:generate
> Starting site crawl...
> Loading robots.txt from http://laravel-nine.local/robots.txt
> Enqueued:  1
> Skipped:   0
> Failed:    0
> Persisted: 0
> 
> Resources:
> Writing sitemap.xml into public directory...
> Sitemap generation completed.

but I am still not sure if it is working properly
so, you need to look at the changes

**Comment by spekulatius** [comment]
Hello @DmitrySidorenkoShim,

thanks for pushing this ahead. I'd wait a bit more on the PR for the spider. It's the core component behind the package. Then we can continue on this package to finish the upgrade.

Cheers,
Peter

**Comment by DmitrySidorenkoShim** [comment]
good news:
my [PR was merged](https://github.com/mvdbos/php-spider/pull/83) by [mvdbos](https://github.com/mvdbos)

so, what would be the workflow?
the same, create fork make all changes and create PR from fork to your package?

waiting for the new version for 'mvdbos/php-spider' package

**Comment by spekulatius** [comment]
Awesome, thanks for pushing this forward. Your next steps sound good to me. With the new tagged version everything should be in place to get started 👍️

**Comment by DmitrySidorenkoShim** [comment]
@spekulatius I created [Pull Request](https://github.com/bringyourownideas/laravel-sitemap/pull/10)

can you, please check if it is ok
or let me know if I need to change something?

**Comment by spekulatius** [comment]
I think this can be closed, thank you @DmitrySidorenkoShim
